spring:
  application:
    name: dev
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf8&useSSL=false&useServerPrepStmts=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: root
          password: xhh1999.02.10
---
spring:
  redis:
    # 地址
    host:
    username:
    password:
    # 端口
    port:
    # 数据库索引  
    database: 0
    # 连接超时时间
    connect-timeout: 10s
    lettuce:
      pool:
        # 连接池最小空闲时间
        min-idle: 0
        # 连接池最大空闲时间
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（负数表示没有限制）
        max-wait: -1ms